In [1]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import FinanceDataReader as fdr

In [2]:
BASE_URL = 'https://finance.naver.com/sise/sise_market_sum.nhn?sosok='

KOSPI_CODE = 0
KOSDAK_CODE = 1
START_PAGE = 1
field = []

def main(code):
    res = requests.get(BASE_URL + str(code) + '&page=' + str(START_PAGE))
    page_soup = BeautifulSoup(res.text, 'lxml')
    
    total_page_num = page_soup.select_one('td.pgRR > a')
    total_page_num = int(total_page_num.get('href').split('=')[-1])
    
    ipt_html = page_soup.select_one('div.subcnt_sise_item_top')
    global fields
    fields = [item.get('value') for item in ipt_html.select('input')]
    
    result = [crawl(code,str(page)) for page in range(1, total_page_num + 1)]
    
    df = pd.concat(result, axis = 0, ignore_index = True)
    return df
    
def crawl(code, page):
    global fields
    data = {'menu': 'market_sum',
            'fieldIds': fields,
            'returnUrl': BASE_URL + str(code) + "&page=" + str(page)}
    
    res = requests.post('https://finance.naver.com/sise/field_submit.nhn', data = data)
    page_soup = BeautifulSoup(res.text, 'lxml')
    
    table_html = page_soup.select_one('div.box_type_l')
    
    header_data = [item.get_text().strip() for item in table_html.select('thead th')][1:-1]
    
    inner_data = [item.get_text().strip() for item in table_html.find_all(lambda x:
                                                                            (x.name == 'a' and
                                                                             'tltle' in x.get('class', [])) or
                                                                            (x.name == 'td' and
                                                                             'number' in x.get('class', []))
                                                                            )]
    no_data = [item.get_text().strip() for item in table_html.select('td.no')]
    number_data = np.array(inner_data)
    
    number_data.resize(len(no_data), len(header_data))
    
    df = pd.DataFrame(data = number_data, columns = header_data)
    return df
main(KOSPI_CODE)

,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,고가,...,주당순이익,보통주배당금,매출액증가율,영업이익증가율,외국인비율,PER,ROE,ROA,PBR,유보율
0,삼성전자,"57,400",900,+1.59%,100,"2,691,429","154,525","18,685,880","57,400","57,600",...,"3,196","1,416",-5.49,-52.84,55.79,17.96,8.69,6.28,1.49,"28,856.0"
1,SK하이닉스,"78,600",200,+0.26%,"5,000","267,256","21,003","2,786,930","78,700","79,000",...,"3,140","1,000",-33.27,-86.99,47.09,25.03,4.25,3.14,1.09,"1,287.0"
2,NAVER,"313,500","1,000",-0.32%,100,"102,119","32,178","1,308,247","316,000","318,000",...,"4,290",376,18.02,-24.66,55.18,73.08,10.56,3.58,6.59,"44,216.1"
3,삼성바이오로직스,"777,000","1,000",+0.13%,"2,500","5,156","4,010","85,511","777,000","781,000",...,"5,191",N/A,30.94,64.77,10.23,149.68,4.77,3.41,11.57,"2,539.1"
4,LG화학,"710,000","10,000",-1.39%,"5,000","81,162","58,125","635,302","720,000","726,000",...,"5,801","2,000",1.57,-60.12,35.95,122.39,1.84,1.20,3.13,"4,362.1"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,KBSTAR 팔라듐선물인버스(H),"5,475",25,+0.46%,0,3,0,"1,102","5,475","5,475",...,N/A,N/A,N/A,N/A,0.00,N/A,N/A,N/A,N/A,N/A
1559,ARIRANG 200동일가중,"8,730",0,0.00%,0,0,0,76,"8,730","8,730",...,N/A,N/A,N/A,N/A,0.00,N/A,N/A,N/A,N/A,N/A
1560,KBSTAR 200금융,"6,785",85,+1.27%,0,2,0,"3,821","6,750","6,785",...,N/A,N/A,N/A,N/A,0.00,N/A,N/A,N/A,N/A,N/A
1561,KBSTAR 200경기소비재,"8,600",70,+0.82%,0,1,0,392,"8,600","8,600",...,N/A,N/A,N/A,N/A,0.00,N/A,N/A,N/A,N/A,N/A
1562,TIGER 지속배당,"12,200",100,+0.83%,0,151,1,"1,607","12,220","12,245",...,N/A,N/A,N/A,N/A,0.00,N/A,N/A,N/A,N/A,N/A

###현재 네이버에 기재된 매출액, 총자산은 마지막 재무제표 결산일을 기준으로 한다

In [3]:
KOSPI = main(KOSPI_CODE)
KOSDAK = main(KOSDAK_CODE)

In [4]:
KOSPI = KOSPI.replace('N/A',np.nan).dropna(axis = 0)
KOSPI['PER'] = KOSPI['PER'].str.replace(',','').astype('float64')
KOSPI['ROE'] = KOSPI['ROE'].str.replace(',','').astype('float64')
KOSPI['ROA'] = KOSPI['ROA'].str.replace(',','').astype('float64')
KOSPI['시가총액'] = KOSPI['시가총액'].str.replace(',','').astype('int64')
KOSPI['매출액'] = KOSPI['매출액'].str.replace(',','').astype('int64')
KOSPI['영업이익'] = KOSPI['영업이익'].str.replace(',','').astype('int64')
KOSPI['PSR'] = KOSPI['시가총액'] / KOSPI['매출액']
KOSPI['POR'] = KOSPI['시가총액'] / KOSPI['영업이익']
KOSPI = KOSPI[['종목명','PER','ROE','ROA','PBR','PSR','POR']]
c = ['PER','POR']
KOSPI[c] = KOSPI[c].mask(KOSPI[c] < 0)
KOSPI = KOSPI.dropna(axis = 0)

In [5]:
KOSPI['PBR + PSR'] = KOSPI[['PBR','PSR']].rank(method = 'min').sum(axis = 1)
KOSPI['PBR + PSR + POR'] = KOSPI[['PBR','PSR','POR']].rank(method = 'min').sum(axis = 1)
KOSPI['total_rank'] = (KOSPI[['PER','PBR','PSR']].rank(method = 'min').sum(axis = 1) + KOSPI[['ROE','ROA']].rank(method = 'min',ascending = False).sum(axis = 1))

In [6]:
PBR_PSR = KOSPI[['종목명','PBR','PSR','PBR + PSR']].sort_values(by = 'PBR + PSR')
PBR_PSR = PBR_PSR.drop(['PBR + PSR'],axis = 1)
PBR_PSR.index = list(range(1,len(PBR_PSR)+1))
PBR_PSR

         종목명   PBR        PSR
1       한화생명  0.09   0.055288
2      세아홀딩스  0.14   0.057436
3       동양생명  0.18   0.078686
4        삼천리  0.19   0.086203
5        아세아  0.18   0.107235
..       ...   ...        ...
439     일양약품  7.61   4.845040
440  유나이티드제약  5.99   7.891098
441    NAVER  6.59   7.810325
442    엔씨소프트  6.06  10.530508
443     부광약품  7.99  14.185493

[443 rows x 3 columns]

In [7]:
#PBR_PSR.to_excel('PBR_PSR.xlsx')

In [8]:
PBR_PSR_POR = KOSPI[['종목명','PBR','PSR','POR','PBR + PSR + POR']].sort_values(by = 'PBR + PSR + POR')
PBR_PSR_POR = PBR_PSR_POR.drop(['PBR + PSR + POR'],axis = 1)
PBR_PSR_POR.index = list(range(1,len(PBR_PSR_POR)+1))
#PBR_PSR_POR.to_excel('PBR_PSR_POR.xlsx')

In [9]:
TOTAL = KOSPI.sort_values(by = 'total_rank')
TOTAL = TOTAL.drop(['PBR + PSR','PBR + PSR + POR','total_rank'], axis = 1)
TOTAL.index = list(range(1,len(TOTAL)+1))
#TOTAL.to_excel('TOTAL.xlsx')

In [45]:
KOSPI = fdr.StockListing('KOSPI')
KOSDAQ = fdr.StockListing('KOSDAQ')
Symbol = KOSDAQ['Symbol']
Name = KOSDAQ['Name']
target = [ i for i in zip(Symbol,Name)]
target = pd.DataFrame(target)
target.columns = ['Symbol','Name']

### 코스닥 상위 종목

In [94]:
ALL = pd.read_excel('all case_v2.xlsx')
c = ['매출액','PER(배)','PBR(배)']
ALL[c] = ALL[c].mask(ALL[c] <= 0)
ALL = ALL.dropna(axis = 0)
ALL.index = list(range(1,len(ALL)+1))
ALL = ALL.drop(['당기순이익','영업이익','EPS(원)','발행주식수(보통주)','total_rank'],axis = 1)
ALL

,종목명,PER(배),PBR(배),ROE(%),ROA(%),매출액,시가총액,PSR,POR
1,이글루시큐리티,8.02,1.24,17.61,11.71,771.0,503.622250,0.653207,3.965530
2,우리넷,5.05,0.62,12.85,9.43,496.0,400.403159,0.807264,6.458115
3,삼영엠텍,8.02,1.24,17.61,11.71,771.0,514.800000,0.667704,4.053543
4,코위버,5.16,0.55,12.01,9.93,600.0,798.439200,1.330732,12.878052
5,시큐브,5.05,0.62,12.85,9.43,496.0,591.600000,1.192742,9.541935
...,...,...,...,...,...,...,...,...,...
201,진성티이씨,236.12,3.70,1.66,0.59,439.0,2371.879274,5.402914,50.465516
202,안랩,257.11,1.16,0.46,0.39,627.0,5377.440135,8.576460,215.097605
203,태광,236.12,3.70,1.66,0.59,439.0,3193.250000,7.273918,67.941489
204,한글과컴퓨터,155.11,10.00,6.66,4.45,124.0,4143.256874,33.413362,517.907109
205,대한광통신,276.88,3.99,1.56,0.76,765.0,3942.947250,5.154179,219.052625

### 테마별 수익률 (당일 계속 크롤링)

In [131]:
url = 'https://finance.naver.com/sise/sise_group.nhn?type=upjong'
req = requests.get(url)
session = requests.session()
res = session.get(url)

html = req.text
soup = BeautifulSoup(html, 'html.parser')
a = soup.select('div > #contentarea > #contentarea_left > table > tr > td > a')

name = []
for i in range(0,79):
    title = a[i].get_text().strip()
    name.append(title)

b = soup.select('div > #contentarea > #contentarea_left > table > tr > td > span')

value = []
for i in range(0,79):
    title = b[i].get_text().strip()
    value.append(title)
target1 = [ i for i in zip(name,value)]
target1 = pd.DataFrame(target1)
target1.columns = ['테마명','등락률']

target1.to_excel('실시간 테마별 수익.xlsx')

In [132]:
target1.head(10)

            테마명     등락률
0  독립전력생산및에너지거래  +7.02%
1          전기장비  +5.58%
2            조선  +5.41%
3    생명과학도구및서비스  +5.21%
4            증권  +4.86%
5       디스플레이패널  +4.31%
6     에너지장비및서비스  +3.84%
7            기계  +3.07%
8          통신장비  +2.86%
9     건강관리장비와용품  +2.65%

### 실시간 뉴스 타이틀 크롤링

In [133]:
import urllib.request
import urllib.parse
from bs4 import BeautifulSoup

plusUrl = urllib.parse.quote_plus(input('검색어를 입력하세요:'))

pageNum = 1
count = 1

i = input('몇페이지 크롤링 할까요? : ')

lastPage = int(i) * 10 - 9
while pageNum < lastPage + 1:
    url = f'https://search.naver.com/search.naver?date_from=&date_option=0&date_to=&dup_remove=1&nso=&post_blogurl=&post_blogurl_without=&query={plusUrl}&sm=tab_pge&srchby=all&st=sim&where=post&start={pageNum}'

    html = urllib.request.urlopen(url).read()
    soup = BeautifulSoup(html, 'html.parser')

    title = soup.find_all(class_='sh_blog_title')

    print(f'-----{count}페이지 결과입니다.-----')
    for i in title:
        print(i.attrs['title'])
        print(i.attrs['href'])
    print()
        
    pageNum += 10
    count += 1

검색어를 입력하세요:삼성전자
몇페이지 크롤링 할까요? : 5
-----1페이지 결과입니다.-----
삼성전자 주식 수익률 340배, 35년 장기 투자 그리고 어이없는 양도세 납부.. 그의 이름 양향자..
https://blog.naver.com/djgkrrl1234?Redirect=Log&logNo=222078395976
삼성전자, 상해종합지수, 신한 레버리지 WTI 원유선물ETN, KODEX WTI 원유선물 확인하기~
https://blog.naver.com/horang_j_h?Redirect=Log&logNo=222082813892
2010년에 삼성전자에 투자했었더라면.
https://blog.naver.com/how2invest?Redirect=Log&logNo=222077219143
9월 7일의 기업분석 Letter - 삼성전자(005930)
https://blog.naver.com/ionia17?Redirect=Log&logNo=222082684896
삼성전자? or 테슬라? 응 아냐 엔비디아야!
https://blog.naver.com/peteryim15?Redirect=Log&logNo=222035385112
삼성전자 주가흐름은 왜 지지부진한가?
https://blog.naver.com/masterwu?Redirect=Log&logNo=222074860326
[추억시리즈] 삼성전자 그리고 중소형주
https://tosoha1.blog.me/221769660469
삼성전자 주가 앞으로의 전망이 궁금하다면?
https://blog.naver.com/poohgirlhs?Redirect=Log&logNo=222039528646
삼성전자를 산게 아니고 외국인은 코스피 선물지수를 샀을 뿐이다
https://thyoon55.blog.me/222045613688
삼성전자 -- 엔비디아 훈풍, 비메모리 보폭 확대
https://blog.naver.com/pokara61?Redirect=Log&logNo=222079115275

-----2페이지 결과입니다.-----
화웨이 제재, 삼성전자 반사이익 현실로?
https://blog.naver.com/tech-plus?Redirect=Log&logNo=222056491371
삼성전자주가 만이 과연 정답일까
https://blog.naver.com/jinri3927?Redirect=Log&logNo=222080111756
삼성전자 갤럭시 노트20 구매후기
https://zidane1024.blog.me/222082589936
SK하이닉스 시총 3위로 밀려..삼성전자와 같은 길로 갈까?
https://blog.naver.com/kmsmir04?Redirect=Log&logNo=222066173667
인버스(곱버스) 매도와 삼성전자 확인하기~
https://blog.naver.com/horang_j_h?Redirect=Log&logNo=222082411632
삼성전자 #목표 주가 상승 (feat, 증시 현황)
https://blog.naver.com/alcy18?Redirect=Log&logNo=222080845809
삼성전자, 지금 주식투자 가능할까?
https://blog.naver.com/joooople?Redirect=Log&logNo=221876364900
엔비디아 vs 삼성전자
https://blog.naver.com/peteryim15?Redirect=Log&logNo=222066988311
달러 환율로 삼성전자 주가 예측하기
https://blog.naver.com/campfire365?Redirect=Log&logNo=222071238309
[이벤트] 종목배틀 주식iN ‘SK하이닉스 VS 삼성전자’ 당신의 선택은?
http://blog.hanwhasmartc.com/222071676998

-----3페이지 결과입니다.-----
이제 다시 서울로, 이제 다시 삼성전자로
http://ohboxa.com/222014771651
미국 5G 시장! 삼성전자 버라이즌과 8조 장비계약
https://blog.naver.com/ohyea95?Redirect=Log&logNo=222082838301
삼성전자주가 지금 사도 괜찮을까요?
https://blog.naver.com/kidallae?Redirect=Log&logNo=222078790048
7월 13일의 기업분석 Letter - 삼성전자(005930)
https://blog.naver.com/ionia17?Redirect=Log&logNo=222029672082
내년에 삼성전자 50%나 오른다는데
https://blog.naver.com/mindy0103?Redirect=Log&logNo=222079570648
주린이를 위한 제언 - 08 안전하고 배당 많이 주고 성장하는 회사 소개 -삼성전자, 삼성전자우
https://blog.naver.com/collera?Redirect=Log&logNo=222074245175
삼성전자 하안가?ㅋ. KODEX레버리지와 인버스(곱버스), 그리고 공매에 대해~
https://blog.naver.com/horang_j_h?Redirect=Log&logNo=222059691143
삼성전자 주가, 주식용어 evebitda 공부하기
https://blog.naver.com/shiningkey?Redirect=Log&logNo=222081371359
전 삼성전자 사장의 중국행으로 인한 기술유출 가능성은?
https://blog.naver.com/d2rksider?Redirect=Log&logNo=221998345209
삼성전자 주가 이것만 알면 된다
https://rkfaortm2593.blog.me/222026056681

-----4페이지 결과입니다.-----
삼성전자 차트 분석
https://blog.naver.com/peteryim15?Redirect=Log&logNo=222000629843
유동성과 삼성전자
https://blog.naver.com/hyy4467?Redirect=Log&logNo=222033070384
[주식매수] 삼성전자 우선주, 재매수 완료
https://blog.naver.com/yes2522?Redirect=Log&logNo=222078163631
삼성전자, 美서 '스마트홈 기술' 특허침해 피소
https://blog.naver.com/fee33ff?Redirect=Log&logNo=222076827985
삼성전자, 5G장비 미국에 수출 8조 '잭팟'
https://blog.naver.com/rlqhstyle?Redirect=Log&logNo=222082902874
삼성전자 주식을 약간 샀던 워런 버핏
https://blog.naver.com/yunvestor1?Redirect=Log&logNo=221821441745
4월 8일의 기업분석 Letter - 삼성전자(005930)
https://blog.naver.com/ionia17?Redirect=Log&logNo=221897371817
삼성전자, 미국 버라이즌에서 7.9조 수주 공시
https://dongtaegood.blog.me/222082342084
삼성전자, 포스코케미칼, 애코프로비엠 이번주 정리하기~
https://blog.naver.com/horang_j_h?Redirect=Log&logNo=222047411271
6.3 삼성전자 급등 과연 동학개미의 승리일까?
https://blog.naver.com/collera?Redirect=Log&logNo=221989075271

-----5페이지 결과입니다.-----
보통주 & 우선주 괴리율(ft. 삼성전자, LG생활건강)
https://blog.naver.com/rlsck?Redirect=Log&logNo=222041192079
상반기 KMW의 매출 비중은 노키아 58%, ZTE 19%, 삼성전자 5% 순
https://thyoon55.blog.me/222065370463
이재용 삼성전자 부회장에 대한 구속영장 청구라? 검찰도 두 갈래. 한쪽은 우국파 다른 한쪽은 그 반대/최석태/
https://blog.naver.com/choisttt?Redirect=Log&logNo=221989910504
[경력관리 사례] 삼성전자에서 이직 제의 받고 고민하는 이유는?
https://blog.naver.com/kil8853?Redirect=Log&logNo=221950690865
'급하면 사면 돼'... 삼성전자의 신시장 선점 전략은?
https://blog.naver.com/tech-plus?Redirect=Log&logNo=221790174947
200819 엘지화학우선주 전량매도. 투자처가 애매할때는 삼성전자? / 티씨케이의 급등
https://blog.naver.com/slater12?Redirect=Log&logNo=222065037801
삼성전자 주가, 올해 1·4분기 영업이익 공시
https://blog.naver.com/ceo0027?Redirect=Log&logNo=221894996653
삼성전자 카카오 역배열이냐
http://ohboxa.com/221988551349
[2020 삼성 채용] 삼성전자 등 잇따라 대학가 채용상담...삼성그룹 대졸 공채 다음주 열릴까?
https://blog.naver.com/trues7?Redirect=Log&logNo=222079055643
5월 4일의 기업분석 Letter - 삼성전자(005930)
https://blog.naver.com/ionia17?Redirect=Log&logNo=221945061340